# # # # # # # # #
# Cactus config #
# # # # # # # # #

#
# Common settings
# =========================

# Active Plugins
common:
  plugins:
    # - haml
    - csssprites
    - coffeescript
    - sass # sass plugin can also handle scss (see "sass" section below).
    # - less # Only choose sass OR less, not both!
    - imageopti
    - minifyjs
    # - blog

  context_processors:
    - default

  tests:
    - console_log

  # Choose one out of "chrome", "firefox", "opera" or "ie", not used when run in mac os x.
  browser: "chrome"

#
# Plugin specific settings
# =========================
plugins:
  coffeescript:
    build_order:
      - main.coffee
    output_filename: main.js
    command: "coffee --join {output_filename} --compile --output {dir_js} {files}"
    # command_windows will overwrite command if running on windows os:
    command_windows: '"C:/Program Files/nodejs/node.exe" "C:/Program Files/CoffeeScript/bin/coffee" --join {output_filename} --compile --output {dir_js} {files}'

  sass:
    type: sass # choose "sass" or "scss"
    main_file_sass: main.sass
    main_file_scss: main.scss
    main_file_css: main.css
    command: "sass -t compressed {input} {output}"
    # Uncomment for scss
    # command: "scss -t compressed {input} {output}"

    # Currently only used for converting glue's css back to sass
    convert_command: "sass-convert -F {in_format} -T {out_format} {infile} {outfile}"

  less:
    main_file_less: main.less
    main_file_css: main.css
    command: "lessc {input} {output}"

  csssprites:
    # path (relative to static) where the images to generate a sprite from are stored
    input_dir: img/_sprites

    # Directory (relative to static) in which the resulting sprite image is stored
    output_dir: img/sprites

    # Directory (relative to static) in which the resulting sprite css is stored
    css_dir: css/sprites

    # During deploy, omit 'input_dir' if set to true
    dont_deploy_input_dir: true

    # See http://glue.readthedocs.org/en/latest/ratios.html#how-retina-and-ratios-work
    retina: false

    # Glue command to be called. Change this to your needs
    command: "glue --cachebuster --crop {retina} {input_dir} --css={css_dir} --img={output_dir}"

  imageopti:
    command_png: "optipng {files}"
    command_jpg: "jpegoptim -o -t --strip-all {file}"

  blog:
    post_identifier: "posts/**/*.html"

  minifyjs:
    input_filename: main.js
    ouput_filename: main.min.js
    keep_unminified: true
    minify_vendor_scripts: true

#
# Build settings
# =========================
build:
  discard_static:
    - coffee
    - sass
    - scss
    - less

#
# Deployment settings
# All settings can be overwritten in a file called deploy.yml
# See deploy.yml.example for details
# =========================
deploy:
  default:
    type: "ssh|s3"
    host: some.host.name
    port: 22
    path: /path/to/project/on/remote/host
    auth: "password|public-key"
    user: username
    private_key: "{home}/.ssh/id_rsa" #only neccessary for auth=public-key
    s3_access_key: "insert access key here" #only neccessary for type=s3
    s3_secret_key: "insert secret key here" #only neccessary for type=s3
    s3_bucket: "bucket name" #only neccessary for type=s3
    s3_site_domain: "your.amazon.aws.domain" #only neccessary for type=s3
