# # # # # # # # #
# Cactus config #
# # # # # # # # #

#
# Common settings
# =========================

# Active Plugins
common:
  plugins:
    - coffeescript
    - sass
    - imageopti

#
# Plugin specific settings
# =========================
plugins:
  coffeescript:
    build_order:
      - main.coffee
    command: "coffee --join main.js --compile --output {dir_js} {files}"

  sass:
    main_file_sass: main.sass
    main_file_css: main.css
    command: "sass {input} {output}"

  imageopti:
	command_png: "optipng {files}"
	command_jpg: "jpegoptim -o -t --strip-all {file}"